config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  patch 'line_item_increase/:id', to: 'line_items#increase_quantity', as:"line_item_increase"
  patch 'line_item_decrease/:id', to: 'line_items#decrease_quantity', as:"line_item_decrease"
  resources :carts, only: [:destroy]
  get '/my_cart', to: 'carts#show'
  resources :food_items  do  	
  	resources :reviews, only: [:new, :create]
  end
	root 'pages#home'
	get '/contact_us', to: 'pages#contact_us'
	get '/menu', to: 'sections#index'
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
	belongs_to :section
	belongs_to :cuisine
	has_many :line_items
	has_many :reviews
	has_many :orders, through: :line_items
	is_impressionable counter_cache: true, column_name: :views, :unique => :all

	before_destroy :ensure_not_referenced_by_any_line_item

	def self.search(search)
		where("name ILIKE ?", "%#{search}%")
	end

	def average_rate
		if (reviews.count > 0)
			(reviews.collect(&:rate).sum/reviews.count).round(1)
		else
			nil
		end
	end

	private
		def ensure_not_referenced_by_any_line_item
			unless line_items.empty?
				errors.add(:base, 'Line Items present')
				throw :abort
			end
		end
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]
  impressionist :actions=>[:show, :index]
  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
    impressionist(@food_item)
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :description, :price)
    end
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/views/food_items/_food_item.html.erb
<div class="content-item rounded">

	<%= link_to food_item do %>
		<%= image_tag(food_item.img_url, width: "100%", class: "avatar rounded-top")  %>
	<% end %>

	<%= link_to food_item do %>
		<div class="item-title"><%= food_item.name %> - <%= food_item.cuisine.name %></div>
	<% end %>
	
	<div class="item-description"><%= truncate(food_item.description, length: 100) %></div>

	<div class="item-footer">
		<div class="item-count align-middle">
			<i class="fa fa-eye"></i>
			<%= food_item.impressionist_count %>
			&nbsp;
			<i class="fa fa-comments"></i>
			<%= food_item.reviews.count %>
			&nbsp;
			<i class="fa fa-star"></i>
      <%= food_item.average_rate%>

		</div>
		
		<%= button_to number_to_currency(food_item.price, locale: :vi), line_items_path(food_item_id: food_item), {form_class: 'form item-order', class: "btn btn-outline-primary btn-sm", remote: true} %>
	</div>

</div>

app/views/food_items/_form.html.erb
<%= form_for(food_item) do |f| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Food Items</h1>

<div class="content-container">
<% @food_items.each do |food_item| %>
  <%= render(food_item) %>
<% end %>
</div>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<section>
  <div class="card">
    <div class="row">

      <div class="col-md-5">
        <div class="card-img-top post-img">
        	<style>
					.post-img{
						background: url(<%= asset_path @food_item.img_url %>) center no-repeat;
						
					}
					</style>
        </div>
      </div>

      <div class="col-md-7 post-body">
        <div class="card-block">
          <h2 class="card-title"><%= @food_item.name %> - <%= @food_item.cuisine.name %> </h2>
          <p class="card-text">
        		<i class="fa fa-eye"></i>
						<%= @food_item.impressionist_count %>
            &nbsp;&nbsp;
            <i class="fa fa-comments"></i>
            <%= @food_item.reviews.count %>
            &nbsp;&nbsp;
            <i class="fa fa-star"></i>
            <%= @food_item.average_rate%>
    
        	</p>
        </div>
        <ul class = "list-group list-group-flush">
          <li class="list-group-item">
	          <p class="card-text post-description"><%= @food_item.description %></p>
					</li>
					<li class="list-group-item">
            <%= number_to_currency(@food_item.price, format: "%n%u", unit:"VND") %>
					</li>

					<li class="list-group-item">
	          <%= button_to 'Add order',line_items_path(food_item_id: @food_item), {form_class: 'form order', class: "btn btn-outline-primary", remote: true} %>
					</li>
				</ul>
    </div>
  </div>
</section>

<section class="review">
  <div class="card">
    <ul class="list-group list-group-flush">
      
        <%= render @food_item.reviews %>
      
    </ul>

    <div class="card-block">
      <%= render "reviews/form", review: Review.new %>
    </div>
  </div>
</section>