config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  patch 'line_item_increase/:id', to: 'line_items#increase_quantity', as:"line_item_increase"
  patch 'line_item_decrease/:id', to: 'line_items#decrease_quantity', as:"line_item_decrease"
  resources :carts, only: [:destroy]
  get '/my_cart', to: 'carts#show'
  resources :food_items  do  	
  	resources :reviews, only: [:new, :create]
  end
	root 'pages#home'
	get '/contact_us', to: 'pages#contact_us'
	get '/menu', to: 'sections#index'
end

app/models/line_item.rb
class LineItem < ApplicationRecord
	belongs_to :order, optional: true
  belongs_to :food_item, optional: true
  belongs_to :cart
  default_scope { order(created_at: :desc) }
  def total_price
  	food_item.price * quantity
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, except: [:create]

  def create
    food_item = FoodItem.find(params[:food_item_id])
    @line_item = @cart.add_food_item(food_item)

    respond_to do |format|
      if @line_item.save
        format.js 
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        if @line_item.quantity <=0
          @line_item.destroy
        end
        format.html { redirect_to my_cart_path }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end


  def increase_quantity
    @line_item.update_attribute(:quantity, @line_item.quantity+1)
    redirect_to my_cart_path
  end

  def decrease_quantity
    @line_item.update_attribute(:quantity, @line_item.quantity-1)
    if @line_item.quantity <=0
      @line_item.destroy
    end
    redirect_to my_cart_path
  end

  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to my_cart_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:food_item_id, :quantity)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(line_item) do |f| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :food_item_id %>
    <%= f.text_field :food_item_id %>
  </div>

  <div class="field">
    <%= f.label :cart_id %>
    <%= f.text_field :cart_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
  
  <li class="list-group-item">  
    <div class="row">
      <div class="col-sm-3">
        <%= image_tag(line_item.food_item.img_url, class:"img-fluid") %>
      </div>
      <div class="col-sm-4">
        <p><%= line_item.food_item.name %></p>
        <p><%= link_to "Remove", line_item, method: :delete %></p>
      </div>
     
      <div class="col-sm-3">
        
          <%= number_to_currency(line_item.food_item.price, locale: :vi) %>
        
      </div>


      <div class="col-sm-2">
      <%= form_for(line_item, method: :patch) do |f| %>
        <div class="input-group input-group-sm">
          <div class="input-group-prepend">
            <%= link_to "-", line_item_decrease_path(line_item), method: :patch, 
                class: "btn btn-outline-secondary btn-block"%>
          </div>
          <%= f.text_field :quantity, class: "form-control", value: line_item.quantity %>
          <div class="input-group-append">
            <%= link_to "+", line_item_increase_path(line_item), method: :patch, 
                class: "btn btn-outline-secondary btn-block"%>
          
          </div>
        </div>  
      <% end %> 
      </div>
    </div>
  </li>

app/views/line_items/create.js.erb
$('#cart').html("<%=j render 'layouts/cart_text' %>");

app/views/line_items/destroy.js.erb
$('#cart').html("<%=j render 'layouts/cart_text' %>")
$('#line-item').html("<%=j render @cart.line_items %>")

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Food item</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.food_item %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Food item:</strong>
  <%= @line_item.food_item %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>