config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  patch 'line_item_increase/:id', to: 'line_items#increase_quantity', as:"line_item_increase"
  patch 'line_item_decrease/:id', to: 'line_items#decrease_quantity', as:"line_item_decrease"
  resources :carts, only: [:destroy]
  get '/my_cart', to: 'carts#show'
  resources :food_items  do  	
  	resources :reviews, only: [:new, :create]
  end
	root 'pages#home'
	get '/contact_us', to: 'pages#contact_us'
	get '/menu', to: 'sections#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :line_items, dependent: :destroy

	def add_food_item(food_item)
		current_item = line_items.find_by(food_item_id: food_item.id)
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(food_item_id: food_item.id)
		end
		current_item
  end
  
  def shipping_fee
    20000
  end

  def sub_total
    line_items.to_a.sum {|item| item.total_price}
  end
	def total_price
		sub_total + shipping_fee
  end
  
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
	has_many :food_items
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
	belongs_to :section
	belongs_to :cuisine
	has_many :line_items
	has_many :reviews
	has_many :orders, through: :line_items
	is_impressionable counter_cache: true, column_name: :views, :unique => :all

	before_destroy :ensure_not_referenced_by_any_line_item

	def self.search(search)
		where("name ILIKE ?", "%#{search}%")
	end

	def average_rate
		if (reviews.count > 0)
			(reviews.collect(&:rate).sum/reviews.count).round(1)
		else
			nil
		end
	end

	private
		def ensure_not_referenced_by_any_line_item
			unless line_items.empty?
				errors.add(:base, 'Line Items present')
				throw :abort
			end
		end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
	belongs_to :order, optional: true
  belongs_to :food_item, optional: true
  belongs_to :cart
  default_scope { order(created_at: :desc) }
  def total_price
  	food_item.price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :line_items, dependent: :destroy
	validates :name, :address, :email, presence: true

	def add_line_items_from_cart(cart)
      cart.line_items.each do |item|
        item.cart_id = nil
        line_items << item
      end    
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :food_item
end

app/models/section.rb
class Section < ApplicationRecord
	has_many :food_items
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    if @cart.line_items.count < 1
      redirect_to menu_path
    end
  end

  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to menu_url, notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end

  private
    def cart_params
      params.fetch(:cart, {})
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :ensure_cart_isnt_empty, only: :new
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(@cart)

    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        format.html { redirect_to @order }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :address, :email)
    end

    def ensure_cart_isnt_empty
      if @cart.line_items.empty?
        redirect_to menu_url, notice: 'Your cart is empty'
      end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
	end

	def contact_us
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_food_item


  # POST /reviews
  # POST /reviews.json
  def create
    @review = @food_item.reviews.create(review_params)

    if @review.save
      redirect_to food_item_path(@food_item)
    else
      render 'new'
    end
  end

  private
    def set_food_item
      @food_item = FoodItem.find(params[:food_item_id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:username, :content, :food_item_id, :rate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/layouts/_cart_text.html.erb
<%= link_to "Cart(#{@cart.line_items.sum("quantity")})", my_cart_path, method: :get %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag("logo.png", width: '32') %>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if current_page?(root_path) %>">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(menu_path) %>">
          <%= link_to "Menu", menu_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(contact_us_path) %>">
          <%= link_to "Contact us", contact_us_path, class: "nav-link" %>
        </li>
      </ul>
      <span class="navbar-text mr-sm-2" id="cart">
        <%= render 'layouts/cart_text' %>
      </span>
      <form action="/food_items" method="get" class="form-inline my-2 my-lg-0">
        <input name="search" class="form-control mr-sm-2" type="text" placeholder="Search">
        <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
    </div>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KingRestaurant</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>  	
  	<%= render 'layouts/navigation' %>
  	<div class="container">
  		<%= yield %>
  	</div> 	
  </body>
</html>

app/views/pages/contact_us.html.erb
<h1 align="center">Contact Us</h1>

<div class="row">
	<div class="col-sm-6">
		<address>
			<strong>King Restaurant</strong><br>
			(01)-234-567-89 <br>
			46M3 Nguyen Huu Hao Street<br>
			Ho Chi Minh City<br>
			Viet Nam <br>
		</address>
	</div>
	<div class="col-sm-6">
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.6419446813134!2d106.69828195098516!3d10.762053892293643!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752f6b57a5ff3f%3A0x1c2a24678ce3d58a!2zNDZNMyBOZ3V54buFbiBI4buvdSBIw6BvLCBwaMaw4budbmcgNiwgUXXhuq1uIDQsIEjhu5MgQ2jDrSBNaW5oLCBWaeG7h3QgTmFt!5e0!3m2!1svi!2s!4v1497690783552" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
	</div>
</div>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>King Restaurant</h1>
  <%= link_to "Menu", menu_path, class: "btn btn-primary btn-lg btn-xlarge" %>
  <%= link_to "Contact us", contact_us_path, class: "btn btn-danger btn-lg btn-xlarge" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    
  </div>    
<% end %>